// Suggestion lists for the Student wizard's autocompletes.
//
// Intentionally curated and short — these are *seed lists* to reduce
// typing. Students can always type a value not in the list; the input
// accepts free text. We bias toward MENA / global STEM coverage with a
// few well-known names, then fall through to free text.

export const UNIVERSITIES: string[] = [
  "King Saud University",
  "King Abdulaziz University",
  "King Fahd University of Petroleum and Minerals",
  "King Abdullah University of Science and Technology",
  "Princess Nourah bint Abdulrahman University",
  "Imam Abdulrahman Bin Faisal University",
  "Prince Sultan University",
  "Effat University",
  "Alfaisal University",
  "American University in Cairo",
  "Cairo University",
  "Ain Shams University",
  "University of Jordan",
  "American University of Beirut",
  "Massachusetts Institute of Technology",
  "Stanford University",
  "Harvard University",
  "Carnegie Mellon University",
  "University of California, Berkeley",
  "ETH Zurich",
  "University of Cambridge",
  "University of Oxford",
  "Imperial College London",
  "Technical University of Munich",
  "University of Toronto",
  "National University of Singapore",
];

export const DEGREES: string[] = [
  "Bachelor of Science (BSc)",
  "Bachelor of Arts (BA)",
  "Bachelor of Engineering (BEng)",
  "Bachelor of Computer Science (BCS)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Commerce (BCom)",
  "Bachelor of Architecture (BArch)",
  "Associate Degree",
  "Diploma",
  "Master of Science (MSc)",
  "Master of Arts (MA)",
  "Master of Engineering (MEng)",
  "Master of Business Administration (MBA)",
  "Doctor of Philosophy (PhD)",
];

export const MAJORS: string[] = [
  "Computer Science",
  "Computer Engineering",
  "Software Engineering",
  "Information Systems",
  "Information Technology",
  "Cybersecurity",
  "Data Science",
  "Artificial Intelligence",
  "Machine Learning",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Industrial Engineering",
  "Chemical Engineering",
  "Biomedical Engineering",
  "Mathematics",
  "Statistics",
  "Physics",
  "Chemistry",
  "Biology",
  "Economics",
  "Finance",
  "Accounting",
  "Marketing",
  "Management",
  "Business Administration",
  "Architecture",
  "Graphic Design",
  "Communications",
  "Psychology",
];

export const SKILLS: string[] = [
  // Languages
  "Python",
  "JavaScript",
  "TypeScript",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Ruby",
  "PHP",
  "Kotlin",
  "Swift",
  "R",
  "MATLAB",
  "SQL",
  "HTML",
  "CSS",
  // Frameworks
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Node.js",
  "Express",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "Ruby on Rails",
  "Laravel",
  "TensorFlow",
  "PyTorch",
  "scikit-learn",
  "pandas",
  "NumPy",
  // Databases & cloud
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "AWS",
  "Google Cloud",
  "Microsoft Azure",
  "Docker",
  "Kubernetes",
  // Tools
  "Git",
  "Linux",
  "Figma",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Excel",
  "PowerPoint",
  // Soft
  "Public speaking",
  "Team leadership",
  "Project management",
  "Technical writing",
  "Research",
  "Problem solving",
];

export const TECH_STACK = SKILLS; // same pool

export const COURSES: string[] = [
  "Introduction to Programming",
  "Data Structures and Algorithms",
  "Object-Oriented Programming",
  "Database Systems",
  "Operating Systems",
  "Computer Networks",
  "Software Engineering",
  "Web Development",
  "Mobile App Development",
  "Machine Learning",
  "Artificial Intelligence",
  "Computer Graphics",
  "Compilers",
  "Distributed Systems",
  "Cybersecurity Fundamentals",
  "Linear Algebra",
  "Calculus I",
  "Calculus II",
  "Probability and Statistics",
  "Discrete Mathematics",
  "Differential Equations",
  "Microeconomics",
  "Macroeconomics",
  "Financial Accounting",
  "Marketing Principles",
  "Organizational Behavior",
  "Technical Writing",
];

export const LANGUAGES: string[] = [
  "Arabic",
  "English",
  "French",
  "Spanish",
  "German",
  "Italian",
  "Portuguese",
  "Russian",
  "Chinese (Mandarin)",
  "Japanese",
  "Korean",
  "Hindi",
  "Urdu",
  "Turkish",
  "Dutch",
  "Swedish",
  "Norwegian",
  "Polish",
  "Greek",
  "Hebrew",
  "Persian (Farsi)",
];

export const LANGUAGE_PROFICIENCIES: string[] = [
  "Basic",
  "Intermediate",
  "Fluent",
  "Native",
];

export const SKILL_PROFICIENCIES: { value: string; label: string }[] = [
  { value: "1", label: "1 — Beginner" },
  { value: "2", label: "2 — Novice" },
  { value: "3", label: "3 — Intermediate" },
  { value: "4", label: "4 — Advanced" },
  { value: "5", label: "5 — Expert" },
];

export const CERTIFICATES: string[] = [
  "AWS Certified Cloud Practitioner",
  "AWS Certified Solutions Architect – Associate",
  "AWS Certified Developer – Associate",
  "Google Cloud Associate Cloud Engineer",
  "Google Cloud Professional Data Engineer",
  "Microsoft Certified: Azure Fundamentals",
  "Microsoft Certified: Azure Administrator Associate",
  "CompTIA A+",
  "CompTIA Network+",
  "CompTIA Security+",
  "Certified Ethical Hacker (CEH)",
  "Cisco Certified Network Associate (CCNA)",
  "Oracle Certified Associate (OCA)",
  "Project Management Professional (PMP)",
  "Certified ScrumMaster (CSM)",
  "Google Data Analytics Professional Certificate",
  "Google IT Support Professional Certificate",
  "Meta Front-End Developer Professional Certificate",
  "DeepLearning.AI Machine Learning Specialization",
  "IBM Data Science Professional Certificate",
];

export const CERTIFICATE_ISSUERS: string[] = [
  "Amazon Web Services",
  "Google Cloud",
  "Microsoft",
  "CompTIA",
  "EC-Council",
  "Cisco",
  "Oracle",
  "PMI",
  "Scrum Alliance",
  "Coursera",
  "edX",
  "Udacity",
  "DataCamp",
  "DeepLearning.AI",
  "IBM",
  "Meta",
];
